version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: "deps(go):"
    groups:
      golang:
          patterns:
            - "golang.org/x/*"
            - "google.golang.org/*"
