linters:
  disable-all: true
  enable:
    - asciicheck
    - copyloopvar
    - depguard
    - dupl
    - forbidigo
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - unused
    - whitespace

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: "Deprecated: As of Go 1.16, the same functionality is now provided by package `io` or package `os`."
  funlen:
    lines: 240
    statements: 160
  lll:
    line-length: 240
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/go-extras/go-kit)
  gocognit:
    min-complexity: 20
  gocritic:
    enabled-checks:
      - badLock
      - badRegexp
      - badSorting
      - badSyncOnceFunc
      - deferInLoop
      - dynamicFmtString
      - emptyDecl
      - filepathJoin
  gocyclo:
    min-complexity: 20
  importas:
    no-unaliased: true
  nakedret: # Discussions on why naked return can be a problem: https://github.com/golang/go/issues/21291
    max-func-lines: 2 # few lines with bare return can be fine for some super short logicless functions
  nolintlint:
    allow-no-explanation:
      # the following linters are allowed without explanations because usually there's nothing to explain
      - errcheck
      - lll
    require-explanation: true
    require-specific: true
  nestif:
    min-complexity: 6
  revive:
    severity: error
    # See https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
    rules:
      - name: atomic
        disabled: false
      - name: bare-return
        disabled: true # covered by nakedret linter
      - name: blank-imports
        disabled: false
      - name: bool-literal-in-expr
        disabled: false
      - name: confusing-results
        disabled: false
      - name: constant-logical-expr
        disabled: false
      - name: context-keys-type
        disabled: false
      - name: datarace
        disabled: false
      - name: deep-exit
        disabled: false
      - name: defer
        disabled: false
      - name: dot-imports
        disabled: false
      - name: duplicated-imports
        disabled: false
      - name: early-return
        disabled: false
      - name: empty-block
        disabled: false
      - name: empty-lines
        disabled: false
      - name: enforce-map-style
        disabled: false
        arguments:
          - make
      - name: enforce-repeated-arg-type-style
        disabled: false
        arguments:
          - short
      - name: enforce-slice-style
        disabled: false
        arguments:
          - make
      - name: error-naming
        disabled: false
      - name: error-return
        disabled: false
      - name: error-strings
        disabled: false
      - name: filename-format
        disabled: false
        arguments:
          - "^[_a-z][_a-z0-9]*.go$"
      - name: flag-parameter
        disabled: false
      - name: function-result-limit
        disabled: false
        arguments:
          - 3
      - name: get-return
        disabled: false
      - name: identical-branches
        disabled: false
      - name: if-return
        disabled: false
      - name: indent-error-flow
        disabled: false
      - name: import-alias-naming
        disabled: false
        arguments:
          - # require aliases to be lowercased alphanumeric values (the first symbol is always a letter)
            allowRegex: '^[a-z][a-z0-9]*$'
            # disallow v1 (or vN, where N is a number) prefixes
            denyRegex: '^v\d+$'
      - name: import-shadowing
        disabled: false
      - name: increment-decrement
        disabled: false
      - name: indent-error-flow
        disabled: false
        arguments:
          - preserveScope
      - name: modifies-value-receiver
        disabled: false
      - name: optimize-operands-order
        disabled: false
      - name: range
        disabled: false
      - name: receiver-naming
        disabled: false
        arguments:
          - maxLength: 2
      - name: redefines-builtin-id
        disabled: false
      - name: redundant-import-alias
        disabled: false
      #- name: redundant-build-tag # not supported in golangci-lint
      #  disabled: false
      - name: string-of-int
        disabled: false
      - name: struct-tag
        disabled: false
      - name: superfluous-else
        disabled: false
      - name: time-equal
        disabled: false
      - name: unchecked-type-assertion
        disabled: false
        arguments:
          - acceptIgnoredAssertionResult: true
      - name: unconditional-recursion
        disabled: false
      - name: unexported-naming
        disabled: false
      - name: unexported-return
        disabled: false
      - name: unnecessary-stmt
        disabled: false
      - name: unreachable-code
        disabled: false
      - name: unused-parameter
        disabled: false
        arguments:
          - allowRegex: "^_"
      - name: unused-receiver
        disabled: false
      - name: use-any
        disabled: false
      - name: useless-break
        disabled: false
      - name: var-naming
        disabled: false
      - name: waitgroup-by-value
        disabled: false
  staticcheck:
    # SAxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    checks: [ "all", "-ST1000", "-ST1003", "-ST1016" ]
  stylecheck:
    # SAxxxx checks in https://staticcheck.io/docs/checks/#ST
    checks: [ "all", "-ST1005" ]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go$
      linters:
        - funlen
        - gocognit
        - gocritic
        - gocyclo
        - lll
        - nestif

run:
  concurrency: 8
  go: '1.23'
  timeout: 5m
